import { Prisma, PurchaseOrderStatus } from '@car-parts/database';
export interface PurchaseOrderQueryParams {
    status?: PurchaseOrderStatus;
    supplierId?: string;
    destinationWarehouseId?: string;
    poNumber?: string;
    dateFrom?: Date;
    dateTo?: Date;
    page?: number;
    limit?: number;
    sortBy?: 'createdAt' | 'expectedDeliveryDate' | 'grandTotal' | 'poNumber' | 'status';
    sortOrder?: 'asc' | 'desc';
}
export declare class PurchaseOrderRepository {
    static findPurchaseOrders(params?: PurchaseOrderQueryParams, tx?: Prisma.TransactionClient): Promise<{
        orders: ({
            supplier: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                displayName: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                notes: string | null;
                currency: string;
                taxId: string | null;
                addressLine1: string | null;
                addressLine2: string | null;
                subdistrict: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                country: string;
                code: string;
                leadTimeDays: number | null;
                contactName: string | null;
                paymentTerms: string | null;
            };
            _count: {
                goodsReceipts: number;
                items: number;
            };
            destinationWarehouse: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                addressLine1: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                code: string;
            };
            createdByUser: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                displayName: string | null;
            } | null;
            approvedByUser: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                displayName: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            rejectionReason: string | null;
            poNumber: string;
            supplierId: string;
            destinationWarehouseId: string;
            currency: string;
            subtotal: Prisma.Decimal;
            discountTotal: Prisma.Decimal;
            taxTotal: Prisma.Decimal;
            shippingCost: Prisma.Decimal;
            otherCost: Prisma.Decimal;
            grandTotal: Prisma.Decimal;
            termsAndConditions: string | null;
            expectedDeliveryDate: Date | null;
            createdByUserId: string | null;
            approvedByUserId: string | null;
            approvedAt: Date | null;
            rejectedByUserId: string | null;
            rejectedAt: Date | null;
            sentByUserId: string | null;
            sentAt: Date | null;
            cancelledByUserId: string | null;
            cancelledAt: Date | null;
            cancellationReason: string | null;
            closedAt: Date | null;
        })[];
        pagination: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    static findById(id: string, tx?: Prisma.TransactionClient): Promise<({
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
        goodsReceipts: ({
            warehouse: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                addressLine1: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                code: string;
            };
            items: {
                id: string;
                createdAt: Date;
                rejectionReason: string | null;
                productId: string;
                supplierSku: string | null;
                unitCost: Prisma.Decimal;
                receivedQuantity: number;
                goodsReceiptId: string;
                purchaseOrderItemId: string;
                acceptedQuantity: number;
                rejectedQuantity: number;
            }[];
            receivedByUser: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                displayName: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            status: string;
            receivedAt: Date;
            warehouseId: string;
            locationId: string | null;
            receiptNumber: string;
            purchaseOrderId: string;
            idempotencyKey: string | null;
            receivedByUserId: string | null;
        })[];
        items: ({
            product: {
                category: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    parentId: string | null;
                    imageUrl: string | null;
                    sortOrder: number;
                };
                brand: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    logoUrl: string | null;
                    websiteUrl: string | null;
                };
            } & {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                sku: string;
                shortDescription: string | null;
                brandId: string;
                categoryId: string;
                barcode: string | null;
                warrantyText: string | null;
                weightGrams: number | null;
                lengthMm: number | null;
                widthMm: number | null;
                heightMm: number | null;
                isPublished: boolean;
            };
            supplierProduct: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                productId: string;
                supplierId: string;
                currency: string;
                supplierSku: string | null;
                purchaseCost: Prisma.Decimal;
                moq: number;
                packSize: number;
                leadTimeDays: number | null;
                isPreferred: boolean;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            productId: string;
            purchaseOrderId: string;
            productName: string;
            lineTotal: Prisma.Decimal;
            supplierSku: string | null;
            supplierProductId: string | null;
            productSku: string;
            unitCost: Prisma.Decimal;
            orderedQuantity: number;
            receivedQuantity: number;
            discount: Prisma.Decimal;
            tax: Prisma.Decimal;
        })[];
        destinationWarehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
        createdByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        approvedByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        rejectedByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        sentByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        cancelledByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: import(".prisma/client").$Enums.PurchaseOrderStatus;
        rejectionReason: string | null;
        poNumber: string;
        supplierId: string;
        destinationWarehouseId: string;
        currency: string;
        subtotal: Prisma.Decimal;
        discountTotal: Prisma.Decimal;
        taxTotal: Prisma.Decimal;
        shippingCost: Prisma.Decimal;
        otherCost: Prisma.Decimal;
        grandTotal: Prisma.Decimal;
        termsAndConditions: string | null;
        expectedDeliveryDate: Date | null;
        createdByUserId: string | null;
        approvedByUserId: string | null;
        approvedAt: Date | null;
        rejectedByUserId: string | null;
        rejectedAt: Date | null;
        sentByUserId: string | null;
        sentAt: Date | null;
        cancelledByUserId: string | null;
        cancelledAt: Date | null;
        cancellationReason: string | null;
        closedAt: Date | null;
    }) | null>;
    static findByIdWithLock(id: string, tx: Prisma.TransactionClient): Promise<({
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
        goodsReceipts: ({
            warehouse: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                addressLine1: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                code: string;
            };
            items: {
                id: string;
                createdAt: Date;
                rejectionReason: string | null;
                productId: string;
                supplierSku: string | null;
                unitCost: Prisma.Decimal;
                receivedQuantity: number;
                goodsReceiptId: string;
                purchaseOrderItemId: string;
                acceptedQuantity: number;
                rejectedQuantity: number;
            }[];
            receivedByUser: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                displayName: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            status: string;
            receivedAt: Date;
            warehouseId: string;
            locationId: string | null;
            receiptNumber: string;
            purchaseOrderId: string;
            idempotencyKey: string | null;
            receivedByUserId: string | null;
        })[];
        items: ({
            product: {
                category: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    parentId: string | null;
                    imageUrl: string | null;
                    sortOrder: number;
                };
                brand: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    logoUrl: string | null;
                    websiteUrl: string | null;
                };
            } & {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                sku: string;
                shortDescription: string | null;
                brandId: string;
                categoryId: string;
                barcode: string | null;
                warrantyText: string | null;
                weightGrams: number | null;
                lengthMm: number | null;
                widthMm: number | null;
                heightMm: number | null;
                isPublished: boolean;
            };
            supplierProduct: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                productId: string;
                supplierId: string;
                currency: string;
                supplierSku: string | null;
                purchaseCost: Prisma.Decimal;
                moq: number;
                packSize: number;
                leadTimeDays: number | null;
                isPreferred: boolean;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            productId: string;
            purchaseOrderId: string;
            productName: string;
            lineTotal: Prisma.Decimal;
            supplierSku: string | null;
            supplierProductId: string | null;
            productSku: string;
            unitCost: Prisma.Decimal;
            orderedQuantity: number;
            receivedQuantity: number;
            discount: Prisma.Decimal;
            tax: Prisma.Decimal;
        })[];
        destinationWarehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
        createdByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        approvedByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        rejectedByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        sentByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
        cancelledByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: import(".prisma/client").$Enums.PurchaseOrderStatus;
        rejectionReason: string | null;
        poNumber: string;
        supplierId: string;
        destinationWarehouseId: string;
        currency: string;
        subtotal: Prisma.Decimal;
        discountTotal: Prisma.Decimal;
        taxTotal: Prisma.Decimal;
        shippingCost: Prisma.Decimal;
        otherCost: Prisma.Decimal;
        grandTotal: Prisma.Decimal;
        termsAndConditions: string | null;
        expectedDeliveryDate: Date | null;
        createdByUserId: string | null;
        approvedByUserId: string | null;
        approvedAt: Date | null;
        rejectedByUserId: string | null;
        rejectedAt: Date | null;
        sentByUserId: string | null;
        sentAt: Date | null;
        cancelledByUserId: string | null;
        cancelledAt: Date | null;
        cancellationReason: string | null;
        closedAt: Date | null;
    }) | null>;
    static findByPoNumber(poNumber: string, tx?: Prisma.TransactionClient): Promise<({
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            productId: string;
            purchaseOrderId: string;
            productName: string;
            lineTotal: Prisma.Decimal;
            supplierSku: string | null;
            supplierProductId: string | null;
            productSku: string;
            unitCost: Prisma.Decimal;
            orderedQuantity: number;
            receivedQuantity: number;
            discount: Prisma.Decimal;
            tax: Prisma.Decimal;
        }[];
        destinationWarehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: import(".prisma/client").$Enums.PurchaseOrderStatus;
        rejectionReason: string | null;
        poNumber: string;
        supplierId: string;
        destinationWarehouseId: string;
        currency: string;
        subtotal: Prisma.Decimal;
        discountTotal: Prisma.Decimal;
        taxTotal: Prisma.Decimal;
        shippingCost: Prisma.Decimal;
        otherCost: Prisma.Decimal;
        grandTotal: Prisma.Decimal;
        termsAndConditions: string | null;
        expectedDeliveryDate: Date | null;
        createdByUserId: string | null;
        approvedByUserId: string | null;
        approvedAt: Date | null;
        rejectedByUserId: string | null;
        rejectedAt: Date | null;
        sentByUserId: string | null;
        sentAt: Date | null;
        cancelledByUserId: string | null;
        cancelledAt: Date | null;
        cancellationReason: string | null;
        closedAt: Date | null;
    }) | null>;
    static create(data: Prisma.PurchaseOrderUncheckedCreateInput, items: Prisma.PurchaseOrderItemUncheckedCreateWithoutPurchaseOrderInput[], tx?: Prisma.TransactionClient): Promise<{
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            productId: string;
            purchaseOrderId: string;
            productName: string;
            lineTotal: Prisma.Decimal;
            supplierSku: string | null;
            supplierProductId: string | null;
            productSku: string;
            unitCost: Prisma.Decimal;
            orderedQuantity: number;
            receivedQuantity: number;
            discount: Prisma.Decimal;
            tax: Prisma.Decimal;
        }[];
        destinationWarehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: import(".prisma/client").$Enums.PurchaseOrderStatus;
        rejectionReason: string | null;
        poNumber: string;
        supplierId: string;
        destinationWarehouseId: string;
        currency: string;
        subtotal: Prisma.Decimal;
        discountTotal: Prisma.Decimal;
        taxTotal: Prisma.Decimal;
        shippingCost: Prisma.Decimal;
        otherCost: Prisma.Decimal;
        grandTotal: Prisma.Decimal;
        termsAndConditions: string | null;
        expectedDeliveryDate: Date | null;
        createdByUserId: string | null;
        approvedByUserId: string | null;
        approvedAt: Date | null;
        rejectedByUserId: string | null;
        rejectedAt: Date | null;
        sentByUserId: string | null;
        sentAt: Date | null;
        cancelledByUserId: string | null;
        cancelledAt: Date | null;
        cancellationReason: string | null;
        closedAt: Date | null;
    }>;
    static update(id: string, data: Prisma.PurchaseOrderUncheckedUpdateInput, tx?: Prisma.TransactionClient): Promise<{
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            productId: string;
            purchaseOrderId: string;
            productName: string;
            lineTotal: Prisma.Decimal;
            supplierSku: string | null;
            supplierProductId: string | null;
            productSku: string;
            unitCost: Prisma.Decimal;
            orderedQuantity: number;
            receivedQuantity: number;
            discount: Prisma.Decimal;
            tax: Prisma.Decimal;
        }[];
        destinationWarehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: import(".prisma/client").$Enums.PurchaseOrderStatus;
        rejectionReason: string | null;
        poNumber: string;
        supplierId: string;
        destinationWarehouseId: string;
        currency: string;
        subtotal: Prisma.Decimal;
        discountTotal: Prisma.Decimal;
        taxTotal: Prisma.Decimal;
        shippingCost: Prisma.Decimal;
        otherCost: Prisma.Decimal;
        grandTotal: Prisma.Decimal;
        termsAndConditions: string | null;
        expectedDeliveryDate: Date | null;
        createdByUserId: string | null;
        approvedByUserId: string | null;
        approvedAt: Date | null;
        rejectedByUserId: string | null;
        rejectedAt: Date | null;
        sentByUserId: string | null;
        sentAt: Date | null;
        cancelledByUserId: string | null;
        cancelledAt: Date | null;
        cancellationReason: string | null;
        closedAt: Date | null;
    }>;
    static generatePoNumber(tx?: Prisma.TransactionClient): Promise<string>;
}
