import { Prisma } from '@car-parts/database';
export interface SupplierQueryParams {
    q?: string;
    search?: string;
    code?: string;
    name?: string;
    isActive?: boolean;
    page?: number;
    offset?: number;
    limit?: number;
    sortBy?: 'name' | 'code' | 'createdAt' | 'updatedAt';
    sortOrder?: 'asc' | 'desc';
}
export declare class SupplierRepository {
    static findSuppliers(params?: SupplierQueryParams, tx?: Prisma.TransactionClient): Promise<{
        suppliers: ({
            _count: {
                supplierProducts: number;
                purchaseOrders: number;
            };
        } & {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        })[];
        pagination: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    static findById(id: string, tx?: Prisma.TransactionClient): Promise<({
        _count: {
            purchaseOrders: number;
        };
        supplierProducts: ({
            product: {
                category: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    parentId: string | null;
                    imageUrl: string | null;
                    sortOrder: number;
                };
                brand: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    logoUrl: string | null;
                    websiteUrl: string | null;
                };
                prices: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    productId: string;
                    currency: string;
                    tier: import(".prisma/client").$Enums.PriceTier;
                    price: Prisma.Decimal;
                    compareAtPrice: Prisma.Decimal | null;
                    costPrice: Prisma.Decimal | null;
                    validFrom: Date | null;
                    validTo: Date | null;
                }[];
            } & {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                sku: string;
                shortDescription: string | null;
                brandId: string;
                categoryId: string;
                barcode: string | null;
                warrantyText: string | null;
                weightGrams: number | null;
                lengthMm: number | null;
                widthMm: number | null;
                heightMm: number | null;
                isPublished: boolean;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            productId: string;
            supplierId: string;
            currency: string;
            supplierSku: string | null;
            purchaseCost: Prisma.Decimal;
            moq: number;
            packSize: number;
            leadTimeDays: number | null;
            isPreferred: boolean;
        })[];
    } & {
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }) | null>;
    static findByCode(code: string, tx?: Prisma.TransactionClient): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    } | null>;
    static create(data: Prisma.SupplierCreateInput, tx?: Prisma.TransactionClient): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }>;
    static update(id: string, data: Prisma.SupplierUpdateInput, tx?: Prisma.TransactionClient): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }>;
    static softDelete(id: string, tx?: Prisma.TransactionClient): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }>;
}
