import { Prisma } from '@car-parts/database';
import { GoodsReceiptQueryParams } from '../repositories/goods-receipt.repository';
export interface ReceiveGoodsItemInput {
    purchaseOrderItemId: string;
    receivedQuantity: number;
    acceptedQuantity?: number;
    rejectedQuantity?: number;
    rejectionReason?: string | null;
}
export interface ReceiveGoodsInput {
    warehouseId?: string;
    locationId?: string | null;
    idempotencyKey?: string | null;
    notes?: string | null;
    items: ReceiveGoodsItemInput[];
}
export declare class GoodsReceiptService {
    static getReceipts(params?: GoodsReceiptQueryParams): Promise<{
        receipts: ({
            location: {
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                warehouseId: string;
                code: string;
                zone: string | null;
                rack: string | null;
                shelf: string | null;
                bin: string | null;
            } | null;
            purchaseOrder: {
                id: string;
                status: import(".prisma/client").$Enums.PurchaseOrderStatus;
                poNumber: string;
                supplier: {
                    name: string;
                    id: string;
                    email: string | null;
                    phone: string | null;
                    displayName: string | null;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    notes: string | null;
                    currency: string;
                    taxId: string | null;
                    addressLine1: string | null;
                    addressLine2: string | null;
                    subdistrict: string | null;
                    district: string | null;
                    province: string | null;
                    postalCode: string | null;
                    country: string;
                    code: string;
                    leadTimeDays: number | null;
                    contactName: string | null;
                    paymentTerms: string | null;
                };
            };
            warehouse: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                addressLine1: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                code: string;
            };
            items: ({
                product: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    sku: string;
                    shortDescription: string | null;
                    brandId: string;
                    categoryId: string;
                    barcode: string | null;
                    warrantyText: string | null;
                    weightGrams: number | null;
                    lengthMm: number | null;
                    widthMm: number | null;
                    heightMm: number | null;
                    isPublished: boolean;
                };
            } & {
                id: string;
                createdAt: Date;
                rejectionReason: string | null;
                productId: string;
                supplierSku: string | null;
                unitCost: Prisma.Decimal;
                receivedQuantity: number;
                goodsReceiptId: string;
                purchaseOrderItemId: string;
                acceptedQuantity: number;
                rejectedQuantity: number;
            })[];
            receivedByUser: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                displayName: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            status: string;
            receivedAt: Date;
            warehouseId: string;
            locationId: string | null;
            receiptNumber: string;
            purchaseOrderId: string;
            idempotencyKey: string | null;
            receivedByUserId: string | null;
        })[];
        pagination: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    static getReceiptById(id: string): Promise<{
        location: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            warehouseId: string;
            code: string;
            zone: string | null;
            rack: string | null;
            shelf: string | null;
            bin: string | null;
        } | null;
        purchaseOrder: {
            supplier: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                displayName: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                notes: string | null;
                currency: string;
                taxId: string | null;
                addressLine1: string | null;
                addressLine2: string | null;
                subdistrict: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                country: string;
                code: string;
                leadTimeDays: number | null;
                contactName: string | null;
                paymentTerms: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            rejectionReason: string | null;
            poNumber: string;
            supplierId: string;
            destinationWarehouseId: string;
            currency: string;
            subtotal: Prisma.Decimal;
            discountTotal: Prisma.Decimal;
            taxTotal: Prisma.Decimal;
            shippingCost: Prisma.Decimal;
            otherCost: Prisma.Decimal;
            grandTotal: Prisma.Decimal;
            termsAndConditions: string | null;
            expectedDeliveryDate: Date | null;
            createdByUserId: string | null;
            approvedByUserId: string | null;
            approvedAt: Date | null;
            rejectedByUserId: string | null;
            rejectedAt: Date | null;
            sentByUserId: string | null;
            sentAt: Date | null;
            cancelledByUserId: string | null;
            cancelledAt: Date | null;
            cancellationReason: string | null;
            closedAt: Date | null;
        };
        warehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
        items: ({
            product: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                sku: string;
                shortDescription: string | null;
                brandId: string;
                categoryId: string;
                barcode: string | null;
                warrantyText: string | null;
                weightGrams: number | null;
                lengthMm: number | null;
                widthMm: number | null;
                heightMm: number | null;
                isPublished: boolean;
            };
            purchaseOrderItem: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                productId: string;
                purchaseOrderId: string;
                productName: string;
                lineTotal: Prisma.Decimal;
                supplierSku: string | null;
                supplierProductId: string | null;
                productSku: string;
                unitCost: Prisma.Decimal;
                orderedQuantity: number;
                receivedQuantity: number;
                discount: Prisma.Decimal;
                tax: Prisma.Decimal;
            };
        } & {
            id: string;
            createdAt: Date;
            rejectionReason: string | null;
            productId: string;
            supplierSku: string | null;
            unitCost: Prisma.Decimal;
            receivedQuantity: number;
            goodsReceiptId: string;
            purchaseOrderItemId: string;
            acceptedQuantity: number;
            rejectedQuantity: number;
        })[];
        receivedByUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: string;
        receivedAt: Date;
        warehouseId: string;
        locationId: string | null;
        receiptNumber: string;
        purchaseOrderId: string;
        idempotencyKey: string | null;
        receivedByUserId: string | null;
    }>;
    static receiveGoods(poId: string, input: ReceiveGoodsInput, actorId: string): Promise<{
        purchaseOrder: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            rejectionReason: string | null;
            poNumber: string;
            supplierId: string;
            destinationWarehouseId: string;
            currency: string;
            subtotal: Prisma.Decimal;
            discountTotal: Prisma.Decimal;
            taxTotal: Prisma.Decimal;
            shippingCost: Prisma.Decimal;
            otherCost: Prisma.Decimal;
            grandTotal: Prisma.Decimal;
            termsAndConditions: string | null;
            expectedDeliveryDate: Date | null;
            createdByUserId: string | null;
            approvedByUserId: string | null;
            approvedAt: Date | null;
            rejectedByUserId: string | null;
            rejectedAt: Date | null;
            sentByUserId: string | null;
            sentAt: Date | null;
            cancelledByUserId: string | null;
            cancelledAt: Date | null;
            cancellationReason: string | null;
            closedAt: Date | null;
        };
        warehouse: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            addressLine1: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            code: string;
        };
        items: {
            id: string;
            createdAt: Date;
            rejectionReason: string | null;
            productId: string;
            supplierSku: string | null;
            unitCost: Prisma.Decimal;
            receivedQuantity: number;
            goodsReceiptId: string;
            purchaseOrderItemId: string;
            acceptedQuantity: number;
            rejectedQuantity: number;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        status: string;
        receivedAt: Date;
        warehouseId: string;
        locationId: string | null;
        receiptNumber: string;
        purchaseOrderId: string;
        idempotencyKey: string | null;
        receivedByUserId: string | null;
    }>;
}
