import { Prisma } from '@car-parts/database';
import { SupplierProductQueryParams } from '../repositories/supplier-product.repository';
export interface CreateSupplierProductInput {
    supplierId: string;
    productId: string;
    supplierSku?: string | null;
    purchaseCost: number | string | Prisma.Decimal;
    currency?: string;
    moq?: number;
    packSize?: number;
    leadTimeDays?: number | null;
    isPreferred?: boolean;
    isActive?: boolean;
}
export interface UpdateSupplierProductInput {
    supplierSku?: string | null;
    purchaseCost?: number | string | Prisma.Decimal;
    currency?: string;
    moq?: number;
    packSize?: number;
    leadTimeDays?: number | null;
    isPreferred?: boolean;
    isActive?: boolean;
}
export declare class SupplierProductService {
    static getSupplierProducts(params?: SupplierProductQueryParams): Promise<{
        items: ({
            product: {
                category: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    parentId: string | null;
                    imageUrl: string | null;
                    sortOrder: number;
                };
                brand: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    logoUrl: string | null;
                    websiteUrl: string | null;
                };
                prices: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    productId: string;
                    currency: string;
                    tier: import(".prisma/client").$Enums.PriceTier;
                    price: Prisma.Decimal;
                    compareAtPrice: Prisma.Decimal | null;
                    costPrice: Prisma.Decimal | null;
                    validFrom: Date | null;
                    validTo: Date | null;
                }[];
            } & {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                sku: string;
                shortDescription: string | null;
                brandId: string;
                categoryId: string;
                barcode: string | null;
                warrantyText: string | null;
                weightGrams: number | null;
                lengthMm: number | null;
                widthMm: number | null;
                heightMm: number | null;
                isPublished: boolean;
            };
            supplier: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                displayName: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                notes: string | null;
                currency: string;
                taxId: string | null;
                addressLine1: string | null;
                addressLine2: string | null;
                subdistrict: string | null;
                district: string | null;
                province: string | null;
                postalCode: string | null;
                country: string;
                code: string;
                leadTimeDays: number | null;
                contactName: string | null;
                paymentTerms: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            productId: string;
            supplierId: string;
            currency: string;
            supplierSku: string | null;
            purchaseCost: Prisma.Decimal;
            moq: number;
            packSize: number;
            leadTimeDays: number | null;
            isPreferred: boolean;
        })[];
        pagination: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    static getSupplierProductById(id: string): Promise<{
        product: {
            category: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                parentId: string | null;
                imageUrl: string | null;
                sortOrder: number;
            };
            brand: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                logoUrl: string | null;
                websiteUrl: string | null;
            };
            prices: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                productId: string;
                currency: string;
                tier: import(".prisma/client").$Enums.PriceTier;
                price: Prisma.Decimal;
                compareAtPrice: Prisma.Decimal | null;
                costPrice: Prisma.Decimal | null;
                validFrom: Date | null;
                validTo: Date | null;
            }[];
        } & {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            slug: string;
            sku: string;
            shortDescription: string | null;
            brandId: string;
            categoryId: string;
            barcode: string | null;
            warrantyText: string | null;
            weightGrams: number | null;
            lengthMm: number | null;
            widthMm: number | null;
            heightMm: number | null;
            isPublished: boolean;
        };
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        productId: string;
        supplierId: string;
        currency: string;
        supplierSku: string | null;
        purchaseCost: Prisma.Decimal;
        moq: number;
        packSize: number;
        leadTimeDays: number | null;
        isPreferred: boolean;
    }>;
    static addSupplierProduct(input: CreateSupplierProductInput, actorId?: string): Promise<{
        product: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            slug: string;
            sku: string;
            shortDescription: string | null;
            brandId: string;
            categoryId: string;
            barcode: string | null;
            warrantyText: string | null;
            weightGrams: number | null;
            lengthMm: number | null;
            widthMm: number | null;
            heightMm: number | null;
            isPublished: boolean;
        };
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        productId: string;
        supplierId: string;
        currency: string;
        supplierSku: string | null;
        purchaseCost: Prisma.Decimal;
        moq: number;
        packSize: number;
        leadTimeDays: number | null;
        isPreferred: boolean;
    }>;
    static updateSupplierProduct(id: string, input: UpdateSupplierProductInput, actorId?: string): Promise<{
        product: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            slug: string;
            sku: string;
            shortDescription: string | null;
            brandId: string;
            categoryId: string;
            barcode: string | null;
            warrantyText: string | null;
            weightGrams: number | null;
            lengthMm: number | null;
            widthMm: number | null;
            heightMm: number | null;
            isPublished: boolean;
        };
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        productId: string;
        supplierId: string;
        currency: string;
        supplierSku: string | null;
        purchaseCost: Prisma.Decimal;
        moq: number;
        packSize: number;
        leadTimeDays: number | null;
        isPreferred: boolean;
    }>;
    static removeSupplierProduct(id: string, actorId?: string): Promise<{
        message: string;
        item: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            productId: string;
            supplierId: string;
            currency: string;
            supplierSku: string | null;
            purchaseCost: Prisma.Decimal;
            moq: number;
            packSize: number;
            leadTimeDays: number | null;
            isPreferred: boolean;
        };
    }>;
    static getMapping(supplierId: string, productId: string): Promise<{
        product: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            slug: string;
            sku: string;
            shortDescription: string | null;
            brandId: string;
            categoryId: string;
            barcode: string | null;
            warrantyText: string | null;
            weightGrams: number | null;
            lengthMm: number | null;
            widthMm: number | null;
            heightMm: number | null;
            isPublished: boolean;
        };
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        productId: string;
        supplierId: string;
        currency: string;
        supplierSku: string | null;
        purchaseCost: Prisma.Decimal;
        moq: number;
        packSize: number;
        leadTimeDays: number | null;
        isPreferred: boolean;
    }>;
}
