import { Prisma } from '@car-parts/database';
import { SupplierQueryParams } from '../repositories/supplier.repository';
export interface CreateSupplierInput {
    code: string;
    name: string;
    displayName?: string | null;
    taxId?: string | null;
    contactName?: string | null;
    email?: string | null;
    phone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    subdistrict?: string | null;
    district?: string | null;
    province?: string | null;
    postalCode?: string | null;
    country?: string;
    paymentTerms?: string | null;
    currency?: string;
    leadTimeDays?: number | null;
    isActive?: boolean;
    notes?: string | null;
}
export interface UpdateSupplierInput {
    code?: string;
    name?: string;
    displayName?: string | null;
    taxId?: string | null;
    contactName?: string | null;
    email?: string | null;
    phone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    subdistrict?: string | null;
    district?: string | null;
    province?: string | null;
    postalCode?: string | null;
    country?: string;
    paymentTerms?: string | null;
    currency?: string;
    leadTimeDays?: number | null;
    isActive?: boolean;
    notes?: string | null;
}
export declare class SupplierService {
    static getSuppliers(params?: SupplierQueryParams): Promise<{
        suppliers: ({
            _count: {
                supplierProducts: number;
                purchaseOrders: number;
            };
        } & {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        })[];
        pagination: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    static getSupplierById(id: string): Promise<{
        _count: {
            purchaseOrders: number;
        };
        supplierProducts: ({
            product: {
                category: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    parentId: string | null;
                    imageUrl: string | null;
                    sortOrder: number;
                };
                brand: {
                    description: string | null;
                    name: string;
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    slug: string;
                    logoUrl: string | null;
                    websiteUrl: string | null;
                };
                prices: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    productId: string;
                    currency: string;
                    tier: import(".prisma/client").$Enums.PriceTier;
                    price: Prisma.Decimal;
                    compareAtPrice: Prisma.Decimal | null;
                    costPrice: Prisma.Decimal | null;
                    validFrom: Date | null;
                    validTo: Date | null;
                }[];
            } & {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                slug: string;
                sku: string;
                shortDescription: string | null;
                brandId: string;
                categoryId: string;
                barcode: string | null;
                warrantyText: string | null;
                weightGrams: number | null;
                lengthMm: number | null;
                widthMm: number | null;
                heightMm: number | null;
                isPublished: boolean;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            productId: string;
            supplierId: string;
            currency: string;
            supplierSku: string | null;
            purchaseCost: Prisma.Decimal;
            moq: number;
            packSize: number;
            leadTimeDays: number | null;
            isPreferred: boolean;
        })[];
    } & {
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }>;
    static createSupplier(input: CreateSupplierInput, actorId?: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }>;
    static updateSupplier(id: string, input: UpdateSupplierInput, actorId?: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        displayName: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        notes: string | null;
        currency: string;
        taxId: string | null;
        addressLine1: string | null;
        addressLine2: string | null;
        subdistrict: string | null;
        district: string | null;
        province: string | null;
        postalCode: string | null;
        country: string;
        code: string;
        leadTimeDays: number | null;
        contactName: string | null;
        paymentTerms: string | null;
    }>;
    static deleteSupplier(id: string, actorId?: string): Promise<{
        message: string;
        supplier: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            notes: string | null;
            currency: string;
            taxId: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            subdistrict: string | null;
            district: string | null;
            province: string | null;
            postalCode: string | null;
            country: string;
            code: string;
            leadTimeDays: number | null;
            contactName: string | null;
            paymentTerms: string | null;
        };
    }>;
}
